name: Lints

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Checkout Main Code 📚
        uses: actions/checkout@v4

      - name: 🐢 Install pnpm 🐢
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: 🐢 Setup Node 🐢
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: 🐢 Install Node Package Dependencies 🐢
        shell: bash
        run: pnpm install

      - name: 🚀 Run linters 🚀
        uses: wearerequired/lint-action@v2
        with:
          prettier: true
